# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170225_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.PaymentType'),
        ),
    ]
